baseURL: http://example.org/
languageCode: en-us
title: Ethereum Testnet
theme: PaperMod

markup:
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    # noClasses: false
    style: monokai

params:
  disableThemeToggle: true
  defaultTheme: dark
  ethereum:
    ethstatsUrl: https://ethstats.testnet0.themerge.dev
    faucetUrl: https://faucet.testnet0.themerge.dev
    rpcUrl: https://rpc.testnet0.themerge.dev
    explorerUrl: https://explorer.testnet0.themerge.dev
    beaconexplorerUrl: https://beaconchain.testnet0.themerge.dev
    consensusmonitorUrl: https://consensusmonitor.testnet0.themerge.dev
    chainName: "Testnet0"
    chainId: "1337332"

menu:
  main:
    - identifier: ethereum-website
      name: ethereum.org
      url: https://ethereum.org
      weight: 30

disableKinds: ["taxonomy", "taxonomyTerm"]

copyright: "This page is "
